# Android Gradle Properties
org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonFinalResIds=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=36
kotlin.code.style=official

# Memory for Kotlin daemon
kotlin.daemon.jvmargs=-Xmx1024m
